iis_web/iis_web/Controllers/AuthController.cs
using iis_web.Connector;
using iis_web.Models;
using iis_web.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace iis_web.Controllers
{
    [JwtFilter]
    [Authorize]
    public class AuthController : Controller
    {
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Login()
        {
            ViewBag.IsValid = true;
            if(User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Rest");
            }
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Login(string username, string password)
        {
            try
            {
                Token t = await AuthConnector.Login(username, password);

                if (t != null)
                {
                    Response.Cookies.Set(new HttpCookie("AuthToken", t.Value));
                    FormsAuthentication.SetAuthCookie(username, true);
                    return RedirectToAction("Index", "Rest");
                }
                ViewBag.IsValid = false;
                return View();
            }
            catch
            {
                ViewBag.IsValid = false;
                return View();
            }
        }

        public ActionResult Logout()
        {
            Response.Cookies.Clear();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

iis_web/iis_web/Controllers/SoapController.cs
using iis_web.CharacterSoapService;
using iis_web.Connector;
using iis_web.Models;
using iis_web.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace iis_web.Controllers
{
    [JwtFilter]
    public class SoapController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Index(SubmitModel model)
        {
            if(ModelState.IsValid)
            {
                CharacterSoapClient client = new CharacterSoapClient();
                var xml = client.Search(model.Term);
                Characters characters = XmlUtils.DeserializeXml<Characters>(xml);
                ViewBag.Characters = characters.CharactersList;
            }

            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Validate()
        {
            Token token = new Token { Value = Request.Cookies.Get("AuthToken").Value };
            bool valid = await MainConnector.Validate(token);
            return Json(valid, JsonRequestBehavior.AllowGet);
        }
    }
}

iis_web/iis_web/Controllers/XmlRpcController.cs
using iis_web.Connector;
using iis_web.Models;
using iis_web.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace iis_web.Controllers
{
    [JwtFilter]
    public class XmlRpcController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(SubmitModel model)
        {
            if(ModelState.IsValid) 
            {
                string temp = await XmlRpcConnector.GetCityTemp(model.Term);
                ViewBag.City = model.Term;
                ViewBag.Temp = temp;
            }
            return View();
        }
    }
}

iis_web/iis_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary  border-bottom border-bottom-dark" data-bs-theme="dark">
        <div class="container-fluid d-flex justify-content-between">
            <a class="navbar-brand" href="#">IIS Projekt</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">@Html.ActionLink("Rest API", "Index", "Rest", null, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("SOAP", "Index", "Soap", null, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("XML-RPC", "Index", "XmlRpc", null, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Logout", "Logout", "Auth", null, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>